import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  typescript: {
    // The validator.ts generated by Next.js incorrectly flags src/pages/ components
    // as Pages Router pages. This disables the TypeScript build-time check while
    // preserving IDE type-checking. All actual type errors in app code are still visible in the IDE.
    ignoreBuildErrors: true,
  },
  async rewrites() {
    const apiBase =
      process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:3001";
    return [
      {
        source: "/api/:path*",
        destination: `${apiBase}/api/:path*`,
      },
    ];
  },
};

export default nextConfig;
