CREATE TABLE "products" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"category" text NOT NULL,
	"subcategory" text NOT NULL,
	"image_url" text,
	"brand" text,
	"price_estimate" real,
	"currency" text DEFAULT 'BGN' NOT NULL,
	"difficulty_level" text NOT NULL,
	"suitable_for" jsonb NOT NULL,
	"not_suitable_for" jsonb NOT NULL,
	"muscles_targeted" jsonb NOT NULL,
	"usage_instructions" jsonb NOT NULL,
	"safety_notes" jsonb NOT NULL,
	"product_type" text NOT NULL,
	"tags" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
