import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  typescript: {
    // The validator.ts generated by Next.js incorrectly flags src/pages/ components
    // as Pages Router pages. This disables the TypeScript build-time check while
    // preserving IDE type-checking. All actual type errors in app code are still visible in the IDE.
    ignoreBuildErrors: true,
  },
  // API routes are now served by this same Next.js app (unified full-stack app).
  // No proxy rewrite needed — /api/* is handled by src/app/api/ route handlers.
  // NEXT_PUBLIC_API_BASE_URL is kept only for the Expo mobile app (external client).
};

export default nextConfig;
